name: Build Installers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Build and package
        run: |
          chmod +x builder_ci.sh
          ./builder_ci.sh

      - name: Upload Offline Installer
        uses: actions/upload-artifact@v3
        with:
          name: Offline Installer
          path: "Pixel Launcher Extended Offline Installer ${{ env.VERSION }}.zip"
