name: Build Installers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and package
        run: |
          chmod +x builder_ci.sh
          ./builder_ci.sh

      - name: Upload Offline Installer
        uses: actions/upload-artifact@v3
        with:
          name: Pixel Launcher Extended Offline Installer
          path: "Pixel Launcher Extended Offline Installer*.zip"

      - name: Upload Online Installer
        uses: actions/upload-artifact@v3
        with:
          name: Pixel Launcher Extended Online Installer
          path: "Pixel Launcher Extended Online Installer*.zip"

      - name: Upload Manual Installer
        uses: actions/upload-artifact@v3
        with:
          name: Pixel Launcher Extended Manual Installer
          path: "Pixel Launcher Extended Manual Installer*.zip"
